version: "3.3"
services:

  postgres:
    image: postgres
    networks:
      - backend
    environment:
      POSTGRES_USER: superheros
      POSTGRES_PASSWORD: superheros
      POSTGRES_DB: superheros
    volumes:
      - $PWD/data:/tmp/data # Used to load data


  superheros:
    build:
      context: .
    image: superheros
    environment:
      POSTGRES_USER: superheros
      POSTGRES_PASSWORD: superheros
      POSTGRES_DB: superheros
      POSTGRES_HOST: postgres
    ports:
      - "8088:8088"
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
